import React from "react"

export const onboard = {
  header: {
    guide: "راهنمای ثبت نام",
    rules: "قوانین و مقررات",
    privacy: "حریم خصوصی",
    about: "درباره ما",
  },
  blueSection: {
    subtitle: "اکوسیستم تامین مالی اکوتام",
    login: "ورود مشتری",
    register: "شروع ثبت نام",
  },
  whiteSection: {
    header: ["ثبت نام غیرحضوری و تمام دیجیتال", <br />, "اکوسیستم تامین مالی اکوتام"],
    ul: "با اکوتام به شبکه تجارت دیجیتال بنگاه به بنگاه بپیوندید",
    li1: " ارتباطات تمام دیجیتال شما با تامین کنندگان و خریداران ",
    li2: "اعتبارسنجی اعضا شبکه تجاری شما",
    li3: "صورتحساب الکترونیک",
    li4: "پرداخت الکترونیکی بنگاه به بنگاه",
    boxes: {
      one: {
        text1: "گام اول",
        text2: "پیش ثبت نام",
      },
      two: {
        text1: "گام دوم",
        text2: "احراز هویت و اصالت مدارک",
      },
      three: {
        text1: "گام سوم",
        text2: "عقد قرارداد و تایید ثبت نام",
      },
    },
  },
  quotesSection: {
    ul: "قبل از ثبت نام نکات زیر را در نظر داشته باشید:",
    li1: "مالکیت شماره همراه می بایست به نام شخص ثبت نام کننده باشد.",
    li2:
      "تصاویر مدارک هویتی ثبت نام کننده و مدارک بنگاه کسب و کاری (شرکت، سازمان دولتی، موسسه و یا صنف) را داشته باشید.",
    li3: ["برای اطلاعات بیشتر ", <a href="#">اینجا</a>, " کلیک کنید"],
  },
  footer: {
    contactus: "تماس با ما:",
    phone1: "۰۲۱ - ۸۸۶۷۸۳۴۶",
    phone2: "۰۲۱ - ۸۸۶۷۷۰۲۶",
  },
  subFooter:
    "©حقوق مادی و معنوی این سامانه به شرکت سامانه کسب و کار فناوری تجارت شایان تعلق دارد و هرگونه کپی برداری محتوا یا اجرایی صرفا با اجازه کتبی از ان مقدور می باشد",
}

export const errors = {
  networkError: "خطا در برقراری ارتباط با سرور",
}

export const dashboardStrings = {
  pageTitles: {
    home: "پیشخوان",
    newUser: "تعریف کاربر جدید",
    networkManagement: "مدیریت شبکه همکاران",
    profileView: "پروفایل شرکت",
    usersList: "مدیریت کاربران",
    invoices: "مدیریت صورتحساب",
    newInvoice: "صورت حساب جدید",
    settingProfile: "تنظیمات پروفایل",
    kartabl: "کارتابل",
    kartablCompanyPreview: "نمایش پروفایل شرکت",
    previewInvoice: "پیش نمایش صورتحساب",
    editInvoice: "ویرایش صورتحساب",
  },
  newUser: {
    firstName: "نام",
    lastName: "نام خانوادگی",
    phone: "شماره همراه",
    email: "آدرس ایمیل",
    jobTitle: "عنوان شغلی",
    role: "نقش کاربر",
    checkboxLabel: "نمایش این کاربر در پروفایل شرکت",
    defineNewRoleButton: "تعریف نقش جدید",
    defineNewUserButton: "تعریف کاربر جدید",
    submitBtn: "تایید",
    cancelBtn: "لغو",
    roles: {
      manager: "مدیر سیستم",
      admin: "ادمین شرکت",
      limited: "دسترسی محدود",
    },
    errors: {
      required: "وارد کردن این فیلد الزامی است",
      requiredRole: "لطفا برای کاربر خود یک نقش انتخاب کنبد",
      email: "آدرس ایمیل اشتباه است",
      phone: "شماره موبایل اشتباه است",
    },
  },
  dialog: {
    title: "تعریف نقش جدید",
    subtitle: "شما می توانید نقش جدید را با استفاده دسترسی ها تعریف کنید.",
    roleTitle: "عنوان نقش",
    fieldTitle: "عنوان فیلد",
    fieldContent1: "انتخاب نشده1",
    fieldContent2: "انتخاب نشده2",
    fieldContent3: "انتخاب نشده3",
    fieldContent4: "انتخاب نشده4",
    selectAll: "انتخاب همه",
  },
  network: {
    ourCoList: "لیست شبکه همکاران ما",
    coSuggestList: "لیست پیشنهادی همکاران",
    searchInCoList: "جستجو در شبکه همکاران من",
    viewAll: "مشاهده همه",
    deleteRelationship: "حذف ارتباط",
    viewCompanyProfile: "نمایش پروفایل شرکت",
    addToNetwork: "اضافه به شبکه همکاران",
  },
  profileView: {
    topBar: {
      text: "در اینجا پروفایل را به صورتی که برای عموم نمایش داده می شود مشاهده می کنید",
      forMeBtn: "نمایش برای من",
    },
    introSection: {
      logo: "لوگو",
      businessName: "نام کسب و کار",
      websiteAddress: "آدرس سایت",
    },
    descriptionSection: {
      businessDescription: "توضیحات",
      description: "توضیحات شرکت",
    },
    addressSection: {
      title: "آدرس شرکت",
      businessAddressProvince: "استان",
      province: "نام استان",
      businessAddressCity: "شهر",
      city: "نام شهر",
      businessAddressPostal: "آدرس",
      address: "آدرس کامل پستی",
      businessPostalCode: "کد پستی",
      postalCode: "کدپستی ۱۰ رقمی",
      businessPhone: "تلفن",
      phone: "۰۲۱-۱۲۳۴۵۶۷۸۹",
    },
    membersSection: {
      title: "اعضای شرکت",
      managerDirector: "مدیرعامل",
      deputyFinance: "معاونت مالی",
      sirMadam: "آقا/خانم ...",
    },
    banner: {
      addBanner: "اضافه کردن تصویر بنر",
    },
    generalProfileViewButton: "نمایش عمومی پروفایل",
    businessInfoSection: {
      business: "نوع بیزینس",
      businessNationalCode: "شناسه ملی",
      numbers: "۱۲۳۴۵۶۷۸۹",
    },
  },
  usersList: {
    usersListTitle: "لیست کاربران",
    search: "جستجو",
    firstName: "نام",
    lastName: "نام خانوادگی",
    phone: "تلفن",
    email: "آدرس ایمیل",
    rule: "نقش",
    status: "وضعیت",
    operation: "عملیات",
    confirm: "فعالسازی کاربران",
    notConfirm: "غیرفعالسازی کاربران",
    notCheckedUsers: "کاربران وارد نشده",
    approvedUsers: "کاربران فعال",
    unapprovedUsers: "کاربران غیرفعال",
    noContent: "اطلاعاتی جهت نمایش وجود ندارد",
    notCheckedUsersNoContent: "کاربر وارد نشده ای در لیست کاربران شما وجود ندارد",
    approvedUsersNoContent: "کاربر فعالی در لیست کاربران شما وجود ندارد",
    unapprovedUsersNoContent: "کاربر غیرفعالی در لیست کاربران شما وجود ندارد",
    successfulVerifyUsers: "عملیات تایید کاربران مورد نظر با موفقیت انجام شد",
    notSuccessfulVerifyUsers: "عملیات عدم تایید کاربران مورد نظر با موفقیت انجام شد",
    successfulVerifyUser: "عملیات تایید کاربر مورد نظر با موفقیت انجام شد",
    notSuccessfulVerifyUser: "عملیات عدم تایید کاربر مورد نظر با موفقیت انجام شد",
    notSelectedUser: "کاربری انتخاب نشده است",
  },
  kartablSetad: {
    btnInHeader: "ثبت شرکت جدید",
    tableTitle: "لیست کسب و کارهای ثبت نام شده",
    search: "جستجو",
    businessName: "نام کسب و کار",
    businessType: "نوع کسب و کار",
    address: "آدرس",
    founderName: "نام موسس",
    registrationNumber: "شماره ثبت",
    status: "وضعیت",
    operation: "عملیات",
    noContent: "اطلاعاتی جهت نمایش وجود ندارد",
    confirm: "تایید کسب و کار",
    notConfirm: "عدم تایید کسب و کار",
    approvedBusinesses: "کسب و کارهای تایید شده",
    unapprovedBusinesses: "کسب و کارهای تایید نشده",
    notCheckedBusinesses: "کسب و کارهای بررسی نشده",
    successfulVerifyCompanies: "عملیات تایید کسب و کار ها با موفقیت انجام شد",
    successfulNotVerifyCompanies: "عملیات عدم تایید کسب و کار ها با موفقیت انجام شد",
    successfulVerifyCompany: "عملیات تایید کسب و کار با موفقیت انجام شد",
    successfulNotVerifyCompany: "عملیات عدم تایید کسب و کار با موفقیت انجام شد",
    notSelectedCompany: "کسب و کاری انتخاب نشده است",
    submitChanges: "ثبت تغییرات",
    changesSubmittedSuccessfully: "تغییرات با موفقیت ثبت شد",
    cancelAndReturn: "لغو تغییرات",
  },
  invoices: {
    sentInvoicesList: "لیست صورتحساب های ارسالی",
    receivedInvoicesList: "لیست صورتحساب های دریافتی",
    search: "جستجو",
    sentInvoices: "صورتحساب های ارسالی",
    receivedInvoices: "صورتحساب های دریافتی",
    costumer: "مشتری",
    orderDate: "تاریخ سفارش",
    price: "مبلغ(ریال)",
    status: "وضعیت",
    latestInvoiceStatus: "آخرین وضعیت صورتحساب",
    newInvoice: "صورتحساب جدید",
    noInvoices: "صورتحسابی برای نمایش وجود ندارد",
    approveInvoice: "تایید صورتحساب",
    rejectInvoice: "رد صورتحساب",
    tableOperations: {
      preview: "پیش نمایش",
      edit: "ویرایش",
      approve: "تایید",
    },
  },
  newInvoice: {
    invoice_number: "شماره صورتحساب",
    invoice_date: "تاریخ",
    sender_business_name: "کسب و کار فروشنده",
    receiver_company_id: "کسب و کار خریدار",
    receiver_user_id: "کاربر دریافت کننده صورتحساب",
    customer_code: "کد مشتری",
    registerProduct: "ثبت کالاها",
    orderList: "لیست سفارشات",
    choseFromOrderList: "انتخاب از لیست سفارش",
    total_price: "قیمت کل (ریال)",
    payment_method: "مدل پرداخت",
    tax: "مالیات (ریال)",
    due_date: "مهلت پرداخت",
    discount: "تخفیف (ریال)",
    discountWithPercentSign: " تخفیف ",
    early_payment: "میزان تخفیف پرداخت زودهنگام",
    prepaidAmountWarningText: " پرداخت زودهنگام",
    penalty: "جریمه تاخیر پرداخت",
    fineWarningText: " تاخیر در پرداخت",
    fineWithPercentSign: " جریمه ",
    final_price: "قیمت کل پس از تخفیف (ریال)",
    rial: "ریال",
    send: "ارسال",
    cancel: "لغو",
    preview: "پیش نمایش",
    choseBuyerFirst: "ابتدا کسب و کار خریدار را انتخاب کنید",
    addItemDialog: {
      title: "تعریف محصول جدید",
      text: "در این قسمت می توانید محصول جدید را برای مشاهده و ثبت در لیست سفارشات تعریف کنید",
      confirm: "تایید",
      inputs: {
        code: "کد کالا",
        name_fa: "نام محصول (فارسی)",
        name_en: "نام محصول (انگلیسی)",
        brand_fa: "نام برند (فارسی)",
        brand_en: "نام برند (انگلیسی)",
        temprature: "دما",
        unit: "واحد",
        placeholders: {
          code: "از این کد تنها در شرکت شما استفاده خواهد شد.",
        },
      },
    },
    table: {
      product: "عنوان کالا",
      unit: "واحد",
      quantity: "تعداد",
      fee: "قیمت واحد (ریال)",
      tax: "مالیات (درصد)",
      discount: "تخفیف (ریال)",
      expire_date: "تاریخ انقضا",
      consumer_price: "قیمت مصرف کننده (ریال)",
      pay_due_date: "مدت پرداخت",
      batch_number: "شماره بج",
      temperature: "دما",
    },
    addNewProduct: "تعریف محصول جدید",
    validationErrors: {
      pleaseCheckForm: "لطفا فرم را بررسی کنید",
      required: "وارد کردن این فیلد الزامی است",
      notValidFormat: "فرمت وارد شده صحیح نمی باشد",
      mustBeNumber: "مقدار وارد شده باید فقط شامل عدد باشد",
      customerPriceMoreThanFee: "قیمت مصرف کننده نباید کمتر از قیمت واحد باشد",
      discountLessThanFee: "تخفیف نباید بیشتر از قیمت واحد باشد",
      noUserFound: "کاربری برای این شرکت یافت نشد",
    },
    successMessages: {
      itemRemovedSuccessfully: "ایتم با موفقیت حذف شد",
    },
  },
  previewInvoice: {
    invoice: "صورتحساب",
    ordersList: "لیست سفارشات",
    edit: "ویرایش",
    return: "بازگشت",
    senderApprove: "تایید صدور",
    receiverApprove: "تایید پرداخت",
    topListKeys: {
      serialHafezeh: "سریال حافظه مالیاتی",
      serialPayaneh: "سریال پایانه فروشگاهی",
      sender_details: "مشخصات فروشنده",
      receiver_details: "مشخصات خریدار",
      user_details: {
        bussinessName: "نام شخص حقیقی/حقوقی",
        bussinessCode: "شماره اقتصادی",
        bussinessNationalCode: "شماره/شناسه ملی",
        completeAddress: "نشانی کامل",
        address: "نشانی",
        province: "استان",
        city: "شهر",
        mainCity: "شهرستان",
        bussinessPostalCode: "کد پستی 10 رقمی",
        bussinessPhone: "شماره تلفن/نمابر",
      },
      tax_number: "شماره مالیاتی",
      invoice_number: "شماره سریال",
      invoice_date: "تاریخ",
      sender_business: "فروشنده",
      customer_code: "کد مشتری",
      buyer_business: "خریدار",
      buyer_name: "دریافت کننده صورتحساب",
      mainUser: "کاربر اصلی",
    },
    bottomListKeys: {
      total_price: "قیمت کل (ریال)",
      payment_method: "مدل پرداخت",
      tax: "مالیات (ریال)",
      due_date: "مهلت پرداخت",
      discount: "تخفیف (ریال)",
      prepaid_amount: "میزان تخفیف پرداخت زودهنگام",
      fine: "جریمه تاخیر پرداخت",
      final_price: "قیمت نهایی (ریال)",
    },
    table: {
      product_id: "شناسه کالا / خدمت",
      product: "شرح کالا یا خدمت",
      unit: "واحد اندازه گیری",
      quantity: "تعداد / مقدار",
      fee: "مبلغ واحد (ریال)",
      total_price: "مبلغ کل (ریال)",
      total_price_after_discount: "مبلغ کل پس از تخفیف (ریال)",
      tax: "نرخ مالیات و عوارض ارزش افزوده",
      tax_in_rials: "جمع مالیات و عوارض ارزش افزوده (ریال)",
      final_price: "جمع کل بعلاوه جمع مالیات و عوارض ارزش افزوده",
      discount: "مبلغ تخفیف (ریال)",
      expire_date: "تاریخ انقضا",
      consumer_price: "قیمت مصرف کننده (ریال)",
      pay_due_date: "مدت پرداخت",
      batch_number: "شماره بج",
      temperature: "دما",
    },
  },
  supplierView: {
    supplierTitle: "داشبورد",
    appBar: {
      saleStatus: "نمایش وضعیت فروش",
      buyStatus: "نمایش وضعیت خرید"
    },
    billSection: {
      bills: "صورتحساب ها",
      draft : "پیش نویس"  , 
      issued :  "صادر شده" , 
      Posted : "ارسال شده" , 
      Outstanding : "تسویه نشده"  ,
      SettledPart : "بخشی تسویه شده" , 
      Cleared : "تسویه شده" , 
      PastDueDate : "سررسید گذشته" , 
      amount  : "تعداد" , 
      price : "ریال"
    } , 
    totalClaims :{
      totalClaims : "کل مطالبات" , 
      TheTotalAmountOfClaims : "مبلغ کل مطالبات:" , 
      Current : "جاری" , 
      timeArrived : "زمان سررسید" , 
      sarresidGozashte : " سررسید گذشته" , 
      DelayTime : "زمان تاخیر" , 
      day : "روز" , 
      CurrentReceivables : "سررسید مطالبات جاری" , 
      TotalBills : "کل صورتحساب ها" , 
      demands : "مطالبات"
    } , 
    myCurrenttsks :{
      myCurrenttsks : "وظایف جاری من"
    }

  }
}

export const tableStrings = {
  view: "نمایش",
  from: "از",
  to: "تا",
  record: "رکورد",
  operation: "عملیات",
  filter: "فیلتر ستون های جدول",
  delete: "حذف انتخاب شده ها",
  exportRows: "گرفتن خروجی",
  row: "ردیف",
}

export const createCompanyProfile = {
  header: {
    title: "پیش ثبت نام",
    subtitle:
      " لطفا اطلاعات شرکت را برای استفاده از سامانه اکوتام تکمیل نمایید. در صورت عدم تکمیل فرایند پیش ثبت نام، می توانید ادامه فرایند را پس از ورود به سامانه، در منوی پروفایل تکمیل نمایید.",
    step1: "اطلاعات کسب و کار",
    step2: "اطلاعات هویتی",
    step3: "اطلاعات مالی و بانکی",
    step4: "انتخاب سرویس",
    step5: "عدم افشای اطلاعات",
    step6: "نمایش قرارداد",
    step7: "مدارک و مستندات",
    step8: "پیش نمایش",
  },
  stepper: {
    nextLabel: "مرحله بعد",
    previousLabel: "مرحله قبل",
    finishLabel: "پایان",
    waitLabel: "لطفا صبر کنید...",
    gotItLabel: "متوجه شدم",
  },
  errors: {
    bussinessNumber: "شماره مجوز صنفی باید ۷ حرف باشد",
    notNumber: "فقط مقادیر عددی مجاز می باشد",
    bussinessCode: "شماره اقتصادی باید ۱۲ رقم باشد",
    bussinessNationalCode: "فرمت وارد شده برای کدملی/شناسه اقتصادی صحیح نیست",
    businessPostalCode: "کدپستی باید ۱۰ رقم باشد",
    phoneNumber: "شماره تلفن باید ۸ رقم باشد",
    logo: "وارد کردن لوگو کسب و کار الزامی است",
    nationalCode: "کد ملی نامعتبر است",
    notValidMobile: "شماره موبایل نامعتبر است",
  },
  content: {
    one: "۱",
    two: "۲",
    pleaseCheckForm: "لطفا فرم را بررسی کنید",
    pleaseWait: "لطفا صبر کنید...",
    unableToUpload: "خطایی در آپلود رخ داد",
    required: "وارد کردن این فیلد الزامی است",
    urlFormat: "فرمت وارد شده برای آدرس وبسایت معتبر نمی باشد",
    mandatory: "(اجباری)",
    submitChanges: "ثبت تغییرات",
    cancelChanges: "لغو تغییرات",
    preview: "پیش نمایش",
    removeUploadedFile: "حذف فایل بارگذاری شده",
    notValidSheba: "شماره شبای وارد شده معتبر نیست",
    notValidNationalCodeFormat: "فرمت وارد شده برای کدملی/شناسه اقتصادی صحیح نیست",
    createdMessage: "اطلاعات شرکت با موفقیت ثبت شد",
    updatedMessage: "اطلاعات شرکت با موفقیت به روزرسانی شد",
    identicalInfo: {
      role: "سمت سازمانی",
      nationalCode: "شماره ملی",
      idNumber: "شماره شناسنامه",
      firstName: "نام",
      lastName: "نام خانوادگی",
      birthDate: "تاریخ تولد",
      cellPhone: "شماره تلفن همراه",
      emailAddress: "آدرس ایمیل",
      signatory: "اطلاعات هویتی صاحبان امضا",
      businessOwnerIdentity: "اطلاعات هویتی صاحب کسب‌وکار",
      roleStartDate: "تاریخ شروع تصدی",
      roleEndDate: "تاریخ پایان تصدی",
    },
    step1: {
      registerAs: "ثبت نام به عنوان",
      buyer: "خریدار (دریافت صورتحساب)",
      seller: "فروشنده (صدور صورتحساب)",
      bothSellerBuyer: "هردو (دریافت و صدور صورتحساب)",
      bussinessInfo: "اطلاعات کسب و کار",
      bussinessAddressTitle: "آدرس کسب و کار",
      bussinessName: "نام کسب و کار",
      websiteAddress: "آدرس سایت",
      emailAddress: "آدرس ایمیل",
      bussinessType: "حوزه فعالیت",
      licenceExpirationDate: "تاریخ انقضا مجوز",
      numberOfEmployees: "تعداد کارکنان شرکت",
      bussinessRegisterNumber: "شماره ثبت",
      bussinessRegisterDate: "تاریخ ثبت",
      bussinessOwner: "نام موسس",
      bussinessNumber: "شماره مجوز صنفی",
      bussinessCode: "شماره اقتصادی",
      bussinessNationalCode: "شناسه ملی کسب و کار",
      serialHafezeh: "سریال حافظه مالیاتی",
      serialPayaneh: "سریال پایانه فروشگاهی",
      personalityType: {
        label: "نوع کسب و کار:",
        legal: "شخصیت حقوقی (شرکت، موسسه، سازمان دولتی)",
        real: "شخصیت حقیقی (اصناف)",
      },
      legalPersonType: "نوع شخصیت حقوقی",
      addNewAddressInfo: "+ اضافه کردن آدرس جدید",
    },
    step2: {
      basicInfo: "اطلاعات پایه",
      bussinessName: "نام کسب و کار",
      websiteAddress: "آدرس سایت",
      bussinessDescriptionOnly: "توضیحات",
      bussinessDescription: "توضیحات\r\nاین توضیحات میتواند شما را به شرکت های دیگر معرفی کند",
      bussinessAddressTitle: "آدرس کسب و کار",
      bussinessAddressProvince: "استان",
      role: "سمت سازمانی",
      roleStartDate: "تاریخ شروع تصدی",
      roleEndDate: "تاریخ پایان تصدی",
      bussinessAddressCity: "شهر/شهرستان",
      defaultAddressTitle: "آدرس دفتر مرکزی",
      bussinessAddressPostal: "آدرس",
      bussinessAddressPostalPlaceholder: "آدرس\r\nآدرس کامل پستی",
      bussinessPostalCode: "کد پستی",
      bussinessPhone: "تلفن",
      logo: "لوگو",
      logoFileType: "نوع فایل png, svg",
      addNewIdentityInfo: "+ افزودن اطلاعات جدید",
    },
    step3: {
      bankInfoTitle: "اطلاعات بانکی",
      bussinessInfoTitle: "اطلاعات مالی",
      bankName: "نام بانک",
      bankAccountType: "نوع حساب",
      bankAccountOwner: "صاحب حساب",
      bankAccountNumber: "شماره حساب",
      bankAccountSHABA: "شماره شبا",
      addNewBankInfo: "+ اضافه کردن اطلاعات بانکی جدید",
      lastYearSale: "میزان فروش سال قبل",
      towYearAgoSale: "میزان فروش دو سال قبل",
      lastYearRegisteredFund: "میزان سرمایه ثبت شده",
    },
    step4: {
      title: "انتخاب سرویس ها",
      selectedServices: "سرویس انتخابی",
      services: {
        einvoice: "صورتحساب الکترونیک ",
        targetCustomer: "شناسایی مشتری ",
        validateCustomer: "اعتبارسنجی مشتری ",
        b2bPayment: "پرداخت B2B",
        removeCheque: "حذف چک",
        reverseFactoring: "فاکتورینگ، فاکتورینگ معکوس",
        scf: "تامین مالی زنجیره تامین",
      },
    },
    step5: {
      title: "توافقنامه عدم افشای اطلاعات",
      informationDisclosure: "عدم افشای اطلاعات",
      logo: "لوگوی شرکت",
      bussinessAddressTitle: "آدرس شرکت",
      agree: "توافقنامه عدم افشای اطلاعات را مطالعه کردم و آن را میپذیرم.",
      agreeContent: "متن توافقنامه عدم افشای اطلاعات",
    },
    step6: {
      title: "پیش نویس قرارداد فیمابین",
      contractContent: "متن قرارداد",
      agree: "پیش نویس قرارداد را مطالعه کردم و آن را می پذیرم.",
    },
    step7: {
      requiredDocumentsTitle: "مدارک مورد نیاز",
      select: "انتخاب",
      docTitle: "عنوان مدرک",
      selectFile: "انتخاب فایل",
      fileTypes: "pdf, .png, .jpg",
      maxFileSize: "حداکثر حجم فایل",
      bussinessDocs: "مدارک و مستندات کسب و کار",
      identityDocs: "مدارک و مستندات هویتی صاحبان کسب و کار",
    },
    waitingStatus: {
      success: "پروفایل شما با موفقیت ثبت شد.",
      result: "نتیجه بررسی مدارک شرکت، حداکثر ظرف ۲ روز کاری\r\nآینده به ایمیل/تلفن همراه شما ارسال خواهد شد.",
      dashboardBtn: "مشاهده داشبورد",
    },
  },
}

export const registerLoginWrapper = {
  contact: "تماس با ما",
  about: "درباره ما",
  condition: "شرایط استفاده",
  dialog: {
    head: "پشتیبانی",
    text: "شما می توانید شماره تماس خود را وارد کنید تا کارشناسان ما در اولین فرصت با شما تماس بگیرند.",
    phone: "شماره تلفن",
    submitBtn: "ارسال درخواست",
  },
}

export const registerStrings = {
  registerText: "به منظور استفاده از سیستمهای مالی اکوتام ثبت نام نمایید",
  ecotomText: "اکوسیستم تامین مالی اکوتام",
  errors: {
    username: "شماره موبایل / ایمیل شما نامعتبر است",
    required: "پر کردن این فیلد الزامی است",
    code: "کد امنیتی اشتباه است",
  },
  form: {
    username: "شماره موبایل / ایمیل",
    usernamePlaceholder: "۰۹۱۲۳۴۵۶۷۸۹",
    securityCode: "کد امنیتی",
    registerBtn: " ثبت نام",
  },
  setPass: {
    label: "رمز عبور",
    choosePass: "انتخاب رمز عبور",
    head: "انتخاب رمز عبور",
    subHead: "برای حساب کاربری خود یک رمز عبور انتخاب نمایید",
    min: "رمز عبور شما کوتاه است",
    submitBtn: "تایید",
  },
  verifyEmail: {
    verifyText: "تایید آدرس ایمیل",
    desc: "لطفا ایمیل خود را چک نمایید وآدرس ایمیل زیر را تایید کنید",
    submitBtn: "مشاهده ایمیل",
    info: ["اگر ایمیلی دریافت نکرده اید لطفا پوشه", <strong>&nbsp;spam&nbsp;</strong>, "خود را نیز چک کنید"],
  },
  verifyMobile: {
    label: "کد تایید",
    header: "تایید شماره تلفن همراه",
    subHeader: " لطفا کد ارسالی به شماره تلفن زیر را وارد نمایید",
    wrongCode: "کد تایید وارد شده نادرست است",
    info: "کد تایید دریافت نکرده اید؟",
    resendCode: "ارسال مجدد کد",
    remainTime: "زمان باقی مانده تا ارسال مجدد کد",
    changeNumber: "تغییر شماره همراه",
  },
  haveAccount: "قبلا ثبت نام کرده اید؟",
  login: "وارد شوید",
}

export const loginStrings = {
  subHeader: "ورود به حساب کاربری",
  header: "اکوسیستم تامین مالی اکوتام",
  forgetPass: "رمز عبور خود را فراموش کرده ام",
  submitBtn: "ورود",
  noAccount: "حساب کاربری ندارید؟",
  register: "ثبت نام کنید",
  verifyPhone: {
    header: "تایید شماره تلفن همراه",
    subHeader: ["به منظور فرآیند تکمیل ورود به سامانه", <br />, "لطفا کد ارسالی به شماره تلفن زیر را وارد نمایید"],
  },
  forgetPassword: {
    header: "رمز عبور خود را فراموش کرده اید؟",
    topText: "لطفا شماره همراه یا ایمیل خود را وارد کنید",
    submitBtn: "تایید",
  },
  newPassword: {
    header: "انتخاب رمز عبور جدید",
    topText: " رمز عبور جدید خود را وارد نمایید",
    submitBtn: "تایید",
    newPass: "رمز عبور",
    reTypePass: "تکرار رمز عبور",
    notMatchedPasswords: "رمز عبور ها یکسان نیستند",
    bottomText: "رمز عبور حداقل شامل ۸ کاراکتر و شامل حروف بزرگ و کوچک باشد",
  },
}
